#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: Pi-hole
# Runs the dnsmasq daemon
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

if hass.debug; then
    exec dnsmasq -7 /etc/dnsmasq.d --no-daemon
else
    exec dnsmasq -7 /etc/dnsmasq.d --keep-in-foreground
fi
